import React from 'react';
import { Info, ShieldCheck, Users, Database, Github, Award } from 'lucide-react';

export const About: React.FC = () => {
  return (
    <div className="space-y-8">
      {/* Header Banner */}
      <div className="glass-panel p-8 space-y-4">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-indigo-500/10 border border-indigo-500/30 rounded-2xl text-indigo-400">
            <Info className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-2xl font-black text-white tracking-tight">About Multilevel AI Authenticity Engine</h3>
            <p className="text-xs text-slate-400 mt-1">
              Hierarchical Digital Forensic Detection Framework
            </p>
          </div>
        </div>

        <p className="text-xs text-slate-300 leading-relaxed">
          The Multilevel AI Authenticity Engine is designed to detect synthetic media generated by Generative Adversarial Networks (StyleGAN, ProGAN) and Latent Diffusion Models (Stable Diffusion, Midjourney, DALL-E, Sora).
        </p>
      </div>

      {/* Target Users Grid */}
      <div className="space-y-4">
        <h4 className="text-sm font-bold text-slate-300 uppercase tracking-wider">
          🎯 Target Audience & Deployments
        </h4>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="glass-card p-5 space-y-2">
            <ShieldCheck className="w-6 h-6 text-indigo-400" />
            <h5 className="font-bold text-sm text-white">Digital Forensic Analysts</h5>
            <p className="text-xs text-slate-400 leading-relaxed">
              Provides multi-domain forensic breakdowns and mathematical risk probabilities for evidentiary inspection.
            </p>
          </div>

          <div className="glass-card p-5 space-y-2">
            <Users className="w-6 h-6 text-cyan-400" />
            <h5 className="font-bold text-sm text-white">Media Verification & Fact Checkers</h5>
            <p className="text-xs text-slate-400 leading-relaxed">
              Rapid bulk processing for newsrooms and platforms to verify user-generated content authenticity.
            </p>
          </div>

          <div className="glass-card p-5 space-y-2">
            <Database className="w-6 h-6 text-purple-400" />
            <h5 className="font-bold text-sm text-white">Cybersecurity & Intelligence Units</h5>
            <p className="text-xs text-slate-400 leading-relaxed">
              Detection of facial swapping deepfakes, identity fraud, and synthetic video manipulation.
            </p>
          </div>
        </div>
      </div>

      {/* Repos & Credits */}
      <div className="glass-panel p-6 space-y-4">
        <h4 className="text-sm font-bold text-slate-300 uppercase tracking-wider">
          ⭐ GitHub Repository & Academic Use
        </h4>
        
        <p className="text-xs text-slate-300 leading-relaxed">
          This system is provided for academic, research, and digital content authentication purposes.
        </p>

        <a
          href="https://github.com/Shreyas1608/Multilevel-AI-Authenticity-Engine"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 px-5 py-2.5 bg-indigo-600/20 hover:bg-indigo-600/30 border border-indigo-500/40 text-indigo-300 rounded-xl text-xs font-bold transition-all"
        >
          <Github className="w-4 h-4" />
          <span>View Source Code on GitHub</span>
        </a>
      </div>
    </div>
  );
};
